{% set name = "mwparserfromhell" %}
{% set version = "0.7.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f4193072e9ea93b9e88f772f60a02125c0602d32890d0bbdcb275ed58c8b3763

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - pip
    - setuptools
    - {{ compiler('c') }}
    - {{ stdlib("c") }} 
  run:
    - python

test:
  imports:
    - mwparserfromhell
    - mwparserfromhell.nodes
    - mwparserfromhell.nodes.extras
    - mwparserfromhell.parser
    - mwparserfromhell.smart_list
    - mwparserfromhell.parser._tokenizer
  requires:
    - pip
  commands:
    - pip check

about:
  home: "https://github.com/earwig/mwparserfromhell"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "MWParserFromHell is a parser for MediaWiki wikicode."
  doc_url: "https://mwparserfromhell.readthedocs.io/en/latest/"
  dev_url: "https://github.com/earwig/mwparserfromhell"

extra:
  recipe-maintainers:
    - earwig
    - mhmohona
